In [4]:
import pandas as pd
import pickle
import numpy as np

ModuleNotFoundError: No module named 'file_utils'

In [7]:
file_path = r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\pickles\B.pkl"
with open(file_path, "rb") as file:
            pickled_data = pickle.load(file)

In [8]:
type(pickled_data)

scipy.sparse.csc.csc_matrix

In [9]:
dense_mat = pickled_data.todense()

In [10]:
dense_mat

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
pickled_data

<2590x15437 sparse matrix of type '<class 'numpy.float64'>'
	with 1588103 stored elements in Compressed Sparse Column format>

In [15]:
pickled_data[345,234]

0.0

In [16]:
print(pickled_data)

  (117, 0)	7.9021e-05
  (227, 0)	7.9853e-05
  (229, 0)	4.727e-05
  (341, 0)	0.0006384224301796184
  (344, 0)	0.0603642931375
  (461, 0)	0.0010417280301161518
  (527, 0)	0.001980907905797905
  (529, 0)	7.110900678768372e-05
  (531, 0)	0.0024509395811778546
  (532, 0)	0.00018767730152283225
  (535, 0)	0.0024990267381343307
  (540, 0)	0.0008447083626478375
  (541, 0)	0.01796717585107851
  (542, 0)	0.0016736359056490377
  (543, 0)	9.031809486333604e-05
  (544, 0)	0.007344684888974129
  (545, 0)	0.0012716033658781874
  (546, 0)	0.01387720399632165
  (547, 0)	0.014911808083220837
  (548, 0)	0.0015593226321956566
  (549, 0)	0.0007165537728542778
  (551, 0)	0.001320329796664732
  (553, 0)	0.00010578177329285867
  (554, 0)	0.011602087045176838
  (559, 0)	0.00016862819584485616
  :	:
  (2183, 15435)	1.7390758572574773e-07
  (2184, 15435)	8.119111020156627e-07
  (231, 15436)	0.000160650061051441
  (655, 15436)	6.3e-08
  (751, 15436)	2.29950016958734e-08
  (760, 15436)	9.44998870548332e-11
  (844,

In [18]:
a = np.array([[1., 2., 3.], [4., 5., -2.],[6., 7., 9.]])

In [19]:
a

array([[ 1.,  2.,  3.],
       [ 4.,  5., -2.],
       [ 6.,  7.,  9.]])

In [20]:
a[0,0]

1.0

In [21]:
a[1]

array([ 4.,  5., -2.])

In [24]:
a[:,1] = np.zeros(3)

In [25]:
a

array([[ 0.,  0.,  0.],
       [ 4.,  0., -2.],
       [ 6.,  0.,  9.]])