In [9]:
import pandas as pd
import os
import pickle
from lxml import objectify
from datetime import datetime

In [2]:
df = pd.read_excel(r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\excel\propanol_eg_aggregatedProcess.xlsx", sheet_name=None)

In [8]:
df['aggr_file_update_meta&admin'].loc[0,'dataSetValidUntil']

2024

In [16]:
datetime.now().isoformat()


'2020-08-13T10:41:09.015953'

In [19]:
datetime.now().astimezone().isoformat()

'2020-08-13T10:43:22.454291+02:00'

In [17]:
datetime.utcnow().isoformat()

'2020-08-13T08:41:12.882341'

In [20]:
ele = df['aggr_file_update_diagramm'].columns[0]

In [134]:
df['aggr_file_update_diagramm'].columns.tolist()

['<referenceToTechnologyFlowDiagrammOrPicture type="source data set" refObjectId="4562465a-92b8-5dc0-b302-692e4e067f38" version="22.00.000" uri="../sources/4562465a-92b8-5dc0-b302-692e4e067f38.xml">\n        <common:shortDescription xml:lang="en">chemical_dataset_diagram</common:shortDescription>\n</referenceToTechnologyFlowDiagrammOrPicture>']

In [135]:
next(iter(df['aggr_file_update_diagramm'].columns))

'<referenceToTechnologyFlowDiagrammOrPicture type="source data set" refObjectId="4562465a-92b8-5dc0-b302-692e4e067f38" version="22.00.000" uri="../sources/4562465a-92b8-5dc0-b302-692e4e067f38.xml">\n        <common:shortDescription xml:lang="en">chemical_dataset_diagram</common:shortDescription>\n</referenceToTechnologyFlowDiagrammOrPicture>'

In [137]:
ele

'<referenceToTechnologyFlowDiagrammOrPicture type="source data set" refObjectId="4562465a-92b8-5dc0-b302-692e4e067f38" version="22.00.000" uri="../sources/4562465a-92b8-5dc0-b302-692e4e067f38.xml">\n        <common:shortDescription xml:lang="en">chemical_dataset_diagram</common:shortDescription>\n</referenceToTechnologyFlowDiagrammOrPicture>'

In [3]:
with open(r"C:\Dropbox (ecoinvent)\ei-int\technical\external\PEF\PEF follow-up\execution\08_xmlCreation\08A_meta&adminProcessFiles\1490942c-2d27-420b-982a-6489d371245f.xml", "r", encoding="utf-8") as xml_f:
    myfile = objectify.parse(xml_f)
    rooty = myfile.getroot()

In [112]:
tech = rooty.processInformation.technology
tech

<Element {http://lca.jrc.it/ILCD/Process}technology at 0x1b58e1e8108>

In [148]:
common = "{http://lca.jrc.it/ILCD/Common}"
root.administrativeInformation[f"{common}commissionerAndGoal"][f"{common}referenceToCommissioner"][f"{common}shortDescription"]._setText("European Commission, DG ENV B1")

In [149]:
root.administrativeInformation[f"{common}commissionerAndGoal"][f"{common}referenceToCommissioner"][f"{common}shortDescription"]

'European Commission, DG ENV B1'

In [153]:
root.administrativeInformation[f"{common}commissionerAndGoal"][f"{common}referenceToCommissioner"].attrib['version'] = '00.00.000'

In [154]:
root.administrativeInformation[f"{common}commissionerAndGoal"][f"{common}referenceToCommissioner"].attrib['version']

'00.00.000'

In [113]:
tech.getchildren()

['1-Propanol is manufactured by the hydrogenation of propanal derived from hydroformylation of ethylene. The hydrogenation of propanal is conventionally carried out as a heterogeneous process in either the vapor or liquid phase over a variety of metal catalysts. Heterogeneous vapor-phase processes are effective at ca. 110 \\xe2\\x80\\x93 150 \\xc2\\xb0C, and 0.14 \\xe2\\x80\\x931.0 MPa at a 20: 1 mole ratio of hydrogen to propanal. Reductions are accomplished in excess hydrogen, and the heat of reaction is removed by circulating the vapor through external heat exchangers or by cooling the reactor internally.\nHydrogen efficiencies are >90 %, with aldehyde conversions as high as 99.9 % and alcohol yields >99 %. The commonly used commercial hydrogenation catalysts include combinations of copper, zinc, nickel, and chromium compounds. Major impurities at vapor-phase process temperatures are dipropyl ether, ethane, and propyl propionate. In addition to reduced zinc oxide and copper oxide ca

In [114]:
len(tech.getchildren())

2

In [119]:
tech.getchildren()

['1-Propanol is manufactured by the hydrogenation of propanal derived from hydroformylation of ethylene. The hydrogenation of propanal is conventionally carried out as a heterogeneous process in either the vapor or liquid phase over a variety of metal catalysts. Heterogeneous vapor-phase processes are effective at ca. 110 \\xe2\\x80\\x93 150 \\xc2\\xb0C, and 0.14 \\xe2\\x80\\x931.0 MPa at a 20: 1 mole ratio of hydrogen to propanal. Reductions are accomplished in excess hydrogen, and the heat of reaction is removed by circulating the vapor through external heat exchangers or by cooling the reactor internally.\nHydrogen efficiencies are >90 %, with aldehyde conversions as high as 99.9 % and alcohol yields >99 %. The commonly used commercial hydrogenation catalysts include combinations of copper, zinc, nickel, and chromium compounds. Major impurities at vapor-phase process temperatures are dipropyl ether, ethane, and propyl propionate. In addition to reduced zinc oxide and copper oxide ca

In [115]:
for i in tech.getchildren():
    print(i.tag)

{http://lca.jrc.it/ILCD/Process}technologyDescriptionAndIncludedProcesses
{http://lca.jrc.it/ILCD/Process}technologicalApplicability


In [121]:
len(list(tech.getiterator()))

3

In [27]:
from xml.etree import ElementTree

In [30]:
from bs4 import BeautifulSoup

In [31]:
soup = BeautifulSoup(ele, "xml")

In [34]:
soup

<?xml version="1.0" encoding="utf-8"?>
<referenceToTechnologyFlowDiagrammOrPicture refObjectId="4562465a-92b8-5dc0-b302-692e4e067f38" type="source data set" uri="../sources/4562465a-92b8-5dc0-b302-692e4e067f38.xml" version="22.00.000">
<shortDescription xml:lang="en">chemical_dataset_diagram</shortDescription>
</referenceToTechnologyFlowDiagrammOrPicture>

In [138]:
import lxml.etree as ET
parser = ET.XMLParser(remove_blank_text=True, recover=True)
tree = ET.ElementTree(ET.fromstring(ele, parser=parser))

In [139]:
tree_ele = tree.getroot()

In [140]:
tree_ele

<Element referenceToTechnologyFlowDiagrammOrPicture at 0x1b58dfb2d88>

In [136]:
from lxml import etree

In [66]:
for i in tech.iterchildren():
    print(i)

The production of distyrylbiphenyl fluorescent whitening agent starts with biphenyl, that is produced along with other aromatic compounds during the refinining of crude oil. Reacting it with chlorine and formaldehyde produces the intermediate 4,4\'-bis(chloromethyl)biphenyl, which reacts with trimethylphosphite to give 4,4\'-bis(dimethoxyphosphonomethyl)biphenyl. This symmetrical biphenylphosphonate is reacted with two molecules of an aromatic aldehyde. In the case of the DSBP under consideration, benzaldehyde-2-sulphonic acid is used, a compound which is produced form 2-chlor-benzaldehyde and sodium sulphite. The two sulphonic acid groups thus introduced give the final product DSBP the desired affinity to adsorb onto cellulose fibres. The commercial product contains 83% active substance (Zah 2007). The same production route is reported in Ullmann\xe2\x80\x99s encyclopedia, volume 25, Siegrist et al. (2003).
The reaction results in the production of 1 kg of reference product plus 1 mol

In [124]:
for c in tech.getchildren():
    print(c.tag)

{http://lca.jrc.it/ILCD/Process}technologyDescriptionAndIncludedProcesses
{http://lca.jrc.it/ILCD/Process}technologicalApplicability


In [110]:
for i in tech.getiterator():
    print(i.tag, '---', i.index(i))

ValueError: Element is not a child of this node.

In [125]:
tech.insert(len(tech.getchildren()) + 1, tree_ele)

In [62]:
for i in tech:
    print(i)

In [126]:
myfile.write(r"D:\ecoinvent_scripts\test.xml",encoding="utf-8",standalone=False,xml_declaration=True,pretty_print=True)

In [127]:
for i in tech.getchildren():
    print(i.tag)

{http://lca.jrc.it/ILCD/Process}technologyDescriptionAndIncludedProcesses
{http://lca.jrc.it/ILCD/Process}technologicalApplicability
referenceToTechnologyFlowDiagrammOrPicture


In [13]:
import lxml.etree as ET

In [48]:
ele1 = df['aggr_file_update_compliance'].columns[0]

In [49]:
ele1

'<complianceDeclarations>\n\t<compliance>\n\t\t<common:referenceToComplianceSystem refObjectId="66279383-8dc3-46c1-80d1-99866cc01e6a" type="source data set" uri="../sources/66279383-8dc3-46c1-80d1-99866cc01e6a.xml" version="29.00.000">\n\t\t  <common:shortDescription xml:lang="en">PEF/OEF implementation, mandatory data 2016-2021</common:shortDescription>\n\t\t</common:referenceToComplianceSystem>\n\t\t<common:approvalOfOverallCompliance>Fully compliant</common:approvalOfOverallCompliance>\n\t\t<common:nomenclatureCompliance>Fully compliant</common:nomenclatureCompliance>\n\t\t<common:methodologicalCompliance>Fully compliant</common:methodologicalCompliance>\n\t\t<common:reviewCompliance>Fully compliant</common:reviewCompliance>\n\t\t<common:documentationCompliance>Fully compliant</common:documentationCompliance>\n\t\t<common:qualityCompliance>Fully compliant</common:qualityCompliance>\n\t</compliance>\n\t<compliance>\n\t\t<common:referenceToComplianceSystem type="source data set" refOb

In [67]:
for found in rooty.modellingAndValidation.getchildren():
    if found.tag == "{http://lca.jrc.it/ILCD/Process}complianceDeclarations":
        found.getparent().remove(found)

In [68]:
for found in rooty.modellingAndValidation.getchildren():
    print(found.tag)

{http://lca.jrc.it/ILCD/Process}LCIMethodAndAllocation
{http://lca.jrc.it/ILCD/Process}dataSourcesTreatmentAndRepresentativeness
{http://lca.jrc.it/ILCD/Process}completeness
{http://lca.jrc.it/ILCD/Process}validation


In [58]:
for found in rooty.modellingAndValidation.complianceDeclarations.getchildren():
    found.getparent().remove(found)

In [5]:
rooty.modellingAndValidation.complianceDeclarations.compliance.getparent()

<Element {http://lca.jrc.it/ILCD/Process}complianceDeclarations at 0x2c5b6c31788>

In [70]:
len(rooty.modellingAndValidation.getchildren())

4

In [71]:
type(rooty.modellingAndValidation)

lxml.objectify.ObjectifiedElement

In [59]:
rooty.modellingAndValidation.complianceDeclarations.getchildren()

[]

In [73]:
mv = rooty.modellingAndValidation

In [74]:
len(mv.getchildren())

4

In [75]:
mv.insert(len(mv.getchildren()) + 1, tree_ele)

In [76]:
mv.getchildren()

[<Element {http://lca.jrc.it/ILCD/Process}LCIMethodAndAllocation at 0x2c5b69fadc8>,
 <Element {http://lca.jrc.it/ILCD/Process}dataSourcesTreatmentAndRepresentativeness at 0x2c5b6aca388>,
 <Element {http://lca.jrc.it/ILCD/Process}completeness at 0x2c5b682b048>,
 <Element {http://lca.jrc.it/ILCD/Process}validation at 0x2c5b826af08>,
 <Element complianceDeclarations at 0x2c5b7f77288>]

In [82]:
mv.getchildren()[0].nsmap

{None: 'http://lca.jrc.it/ILCD/Process',
 'common': 'http://lca.jrc.it/ILCD/Common',
 'ext': 'http://eplca.jrc.ec.europa.eu/ILCD/Extensions/2017',
 'xsi': 'http://www.w3.org/2001/XMLSchema-instance'}

In [87]:
mv.getchildren()[0].nsmap

{None: 'http://lca.jrc.it/ILCD/Process',
 'common': 'http://lca.jrc.it/ILCD/Common',
 'ext': 'http://eplca.jrc.ec.europa.eu/ILCD/Extensions/2017',
 'xsi': 'http://www.w3.org/2001/XMLSchema-instance'}

In [83]:
mv.getchildren()[4].nsmap

{None: 'http://lca.jrc.it/ILCD/Process',
 'common': 'http://lca.jrc.it/ILCD/Common',
 'ext': 'http://eplca.jrc.ec.europa.eu/ILCD/Extensions/2017',
 'xsi': 'http://www.w3.org/2001/XMLSchema-instance'}

In [50]:
parser = ET.XMLParser(recover=True)
tree = ET.ElementTree(ET.fromstring(ele1, parser=parser))
tree_ele = tree.getroot()

In [84]:
help(tree_ele)

Help on _Element object:

class _Element(builtins.object)
 |  Element class.
 |  
 |  References a document object and a libxml node.
 |  
 |  By pointing to a Document instance, a reference is kept to
 |  _Document as long as there is some pointer to a node in it.
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(...)
 |      __contains__(self, element)
 |  
 |  __copy__(self)
 |      __copy__(self)
 |  
 |  __deepcopy__(self, memo)
 |      __deepcopy__(self, memo)
 |  
 |  __delitem__(...)
 |      __delitem__(self, x)
 |      
 |      Deletes the given subelement or a slice.
 |  
 |  __getitem__(...)
 |      Returns the subelement at the given position or the requested
 |      slice.
 |  
 |  __iter__(...)
 |      __iter__(self)
 |  
 |  __len__(...)
 |      __len__(self)
 |      
 |      Returns the number of subelements.
 |  
 |  __repr__(...)
 |      __repr__(self)
 |  
 |  __reversed__(self)
 |      __reversed__(self)
 |  
 |  __set

In [80]:
tree_ele.nsmap[None]

'http://lca.jrc.it/ILCD/Process'

In [55]:
tree_ele.tag

'complianceDeclarations'

In [51]:
for i in tree.iter():
    print(i)

<Element complianceDeclarations at 0x2c5b7f77288>
<Element compliance at 0x2c5b81d9388>
<Element common:referenceToComplianceSystem at 0x2c5b7fecbc8>
<Element common:shortDescription at 0x2c5b7a9be08>
<Element common:approvalOfOverallCompliance at 0x2c5b81d9388>
<Element common:nomenclatureCompliance at 0x2c5b7fecbc8>
<Element common:methodologicalCompliance at 0x2c5b7a9be08>
<Element common:reviewCompliance at 0x2c5b81d9388>
<Element common:documentationCompliance at 0x2c5b7fecbc8>
<Element common:qualityCompliance at 0x2c5b7a9be08>
<Element compliance at 0x2c5b81d9388>
<Element common:referenceToComplianceSystem at 0x2c5b7fecbc8>
<Element common:shortDescription at 0x2c5b81d9208>
<Element common:approvalOfOverallCompliance at 0x2c5b7a9be08>
<Element common:nomenclatureCompliance at 0x2c5b7fecbc8>
<Element common:methodologicalCompliance at 0x2c5b81d95c8>
<Element common:reviewCompliance at 0x2c5b7a9be08>
<Element common:documentationCompliance at 0x2c5b7fecbc8>
<Element common:qualit

In [45]:
len(tree_ele)

7

In [72]:
type(tree_ele)

lxml.etree._Element

In [53]:
tree_ele[0]

<Element compliance at 0x2c5b81d9b48>

In [54]:
tree_ele[1]

<Element compliance at 0x2c5b826a908>

In [60]:
mv = rooty.modellingAndValidation

In [18]:
cd.getchildren()

[]

In [19]:
cd.insert(1, tree_ele)

In [56]:
len(tree_ele)

6

In [30]:
for i in tree.iter():
    print(i.text)


	

	  
PEF/OEF implementation, mandatory data 2016-2021
Fully compliant
Fully compliant
Fully compliant
Fully compliant
Fully compliant
Fully compliant


In [122]:
ele2 = df['aggr_file_update_reviewer'].columns[0]
ele2

'           \n                <common:referenceToNameOfReviewerAndInstitution type="contact data set" refObjectId="52646f69-d9e0-4a6a-ad7f-d2024d11651c" version="01.00.000" uri="../contacts/\t52646f69-d9e0-4a6a-ad7f-d2024d11651c.xml">\n                    <common:shortDescription xml:lang="en">Eric Johnson</common:shortDescription>\n                </common:referenceToNameOfReviewerAndInstitution>                \n                <common:referenceToNameOfReviewerAndInstitution type="contact data set" refObjectId="7fbe898d-3362-474a-bc26-2a05fba4b5d7" version="01.00.000" uri="../contacts/7fbe898d-3362-474a-bc26-2a05fba4b5d7.xml">\n                    <common:shortDescription xml:lang="en">Gregor Wernet</common:shortDescription>\n                </common:referenceToNameOfReviewerAndInstitution>\n                <common:referenceToNameOfReviewerAndInstitution type="contact data set" refObjectId="e0e2442c-9cf2-4783-addb-75060de83d29" version="01.00.000" uri="../contacts/e0e2442c-9cf2-4783-

In [137]:
li = ele2.split('</common:referenceToNameOfReviewerAndInstitution>')
li

['           \n                <common:referenceToNameOfReviewerAndInstitution type="contact data set" refObjectId="52646f69-d9e0-4a6a-ad7f-d2024d11651c" version="01.00.000" uri="../contacts/\t52646f69-d9e0-4a6a-ad7f-d2024d11651c.xml">\n                    <common:shortDescription xml:lang="en">Eric Johnson</common:shortDescription>\n                ',
 '                \n                <common:referenceToNameOfReviewerAndInstitution type="contact data set" refObjectId="7fbe898d-3362-474a-bc26-2a05fba4b5d7" version="01.00.000" uri="../contacts/7fbe898d-3362-474a-bc26-2a05fba4b5d7.xml">\n                    <common:shortDescription xml:lang="en">Gregor Wernet</common:shortDescription>\n                ',
 '\n                <common:referenceToNameOfReviewerAndInstitution type="contact data set" refObjectId="e0e2442c-9cf2-4783-addb-75060de83d29" version="01.00.000" uri="../contacts/e0e2442c-9cf2-4783-addb-75060de83d29.xml">\n                    <common:shortDescription xml:lang="en">Emi

In [140]:
firstitem = "".join((li[0], '</common:referenceToNameOfReviewerAndInstitution>'))
firstitem

'           \n                <common:referenceToNameOfReviewerAndInstitution type="contact data set" refObjectId="52646f69-d9e0-4a6a-ad7f-d2024d11651c" version="01.00.000" uri="../contacts/\t52646f69-d9e0-4a6a-ad7f-d2024d11651c.xml">\n                    <common:shortDescription xml:lang="en">Eric Johnson</common:shortDescription>\n                </common:referenceToNameOfReviewerAndInstitution>'

In [127]:
from lxml import objectify
import itertools

In [141]:
parser = ET.XMLParser(recover=True)
tree = ET.ElementTree(ET.fromstring(firstitem, parser=parser))
tree_ele = tree.getroot()

In [142]:
for i in tree.iter():
    print(i)

<Element common:referenceToNameOfReviewerAndInstitution at 0x2c5b834c9c8>
<Element common:shortDescription at 0x2c5b8283c08>


In [135]:
ET.fromstring(ele2, parser=parser)

<Element common:referenceToNameOfReviewerAndInstitution at 0x2c5b7b0fd48>

In [131]:
parser = ET.XMLParser(recover=True)
it = itertools.chain('<root>', ele2, '</root>')
tree = ET.ElementTree(ET.fromstringlist(it, parser=parser))
tree_ele = tree.getroot()

In [134]:
for i in tree.iter():
    print(i)

<Element common:referenceToNameOfReviewerAndInstitution at 0x2c5b835bb88>
<Element common:shortDescription at 0x2c5b696f288>


In [130]:
tree_ele.tag

'root'

In [121]:
dir(ET)

['AncestorsIterator',
 'AttributeBasedElementClassLookup',
 'C14NError',
 'C14NWriterTarget',
 'CDATA',
 'Comment',
 'CommentBase',
 'CustomElementClassLookup',
 'DEBUG',
 'DTD',
 'DTDError',
 'DTDParseError',
 'DTDValidateError',
 'DocInfo',
 'DocumentInvalid',
 'ETCompatXMLParser',
 'ETXPath',
 'Element',
 'ElementBase',
 'ElementChildIterator',
 'ElementClassLookup',
 'ElementDefaultClassLookup',
 'ElementDepthFirstIterator',
 'ElementNamespaceClassLookup',
 'ElementTextIterator',
 'ElementTree',
 'Entity',
 'EntityBase',
 'Error',
 'ErrorDomains',
 'ErrorLevels',
 'ErrorTypes',
 'Extension',
 'FallbackElementClassLookup',
 'FunctionNamespace',
 'HTML',
 'HTMLParser',
 'HTMLPullParser',
 'LIBXML_COMPILED_VERSION',
 'LIBXML_VERSION',
 'LIBXSLT_COMPILED_VERSION',
 'LIBXSLT_VERSION',
 'LXML_VERSION',
 'LxmlError',
 'LxmlRegistryError',
 'LxmlSyntaxError',
 'NamespaceRegistryError',
 'PI',
 'PIBase',
 'ParseError',
 'ParserBasedElementClassLookup',
 'ParserError',
 'ProcessingInstructio

In [119]:
for i in tree.iter():
    print(i)

<Element common:referenceToNameOfReviewerAndInstitution at 0x2c5b8633488>
<Element common:shortDescription at 0x2c5b8633608>


In [103]:
type(tree_ele)

NoneType

In [19]:
(rooty)

Help on ObjectifiedElement object:

class ObjectifiedElement(lxml.etree.ElementBase)
 |  Main XML Element class.
 |  
 |  Element children are accessed as object attributes.  Multiple children
 |  with the same name are available through a list index.  Example::
 |  
 |     >>> root = XML("<root><c1><c2>0</c2><c2>1</c2></c1></root>")
 |     >>> second_c2 = root.c1.c2[1]
 |     >>> print(second_c2.text)
 |     1
 |  
 |  Note that you cannot (and must not) instantiate this class or its
 |  subclasses.
 |  
 |  Method resolution order:
 |      ObjectifiedElement
 |      lxml.etree.ElementBase
 |      lxml.etree._Element
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __getattr__(...)
 |      Return the (first) child with the given tag name.  If no namespace
 |      is provided, the child will be looked up in the same one as self.
 |  
 | 

In [3]:
with open(r"D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\pickles\indexes.pkl", "rb") as file:
    pickled_data = pickle.load(file)

In [82]:
type(pickled_data)

matrix_builder.Matrix_Index

In [85]:
with open(r"D:\ecoinvent_scripts\indexes.pkl", "rb") as file:
    pickled_new = pickle.load(file)

In [86]:
type(pickled_new)

matrix_index.MatrixIndex

In [112]:
pickled_data.toggle['ie'][0]

('[sulfonyl]urea-compound production', 'RER', '[sulfonyl]urea-compound')

In [111]:
pickled_new.toggle['ie'][0]

('[sulfonyl]urea-compound production', 'RER', '[sulfonyl]urea-compound')

In [87]:
dir(pickled_new)

['LCIA',
 '_MatrixIndex__add_index',
 '_MatrixIndex__read_elemnts',
 '_MatrixIndex__read_indexes_tempalte',
 '_MatrixIndex__to_dfs',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'convert_to_indexes_pickle',
 'df_columns',
 'dfs',
 'ee',
 'ie',
 'index_PEF_df',
 'index_types',
 'toggle',
 'units']

In [79]:
pickled_new['ee']

name         compartment  \
0                      (2,4-dichlorophenoxy)acetic acid    Emissions to air   
1                      (2,4-dichlorophenoxy)acetic acid   Emissions to soil   
2        (R)-2-(4-chloro-2-methylphenoxy)propionic acid   Emissions to soil   
3                       1,1'-dimethyl-4,4'-bipyridinium    Emissions to air   
4                       1,1'-dimethyl-4,4'-bipyridinium   Emissions to soil   
...                                                 ...                 ...   
2585  β-([1,1'-biphenyl]-4-yloxy)-α-tert-butyl-1H-1,...   Emissions to soil   
2586                                    γ-butyrolactone    Emissions to air   
2587                                    γ-butyrolactone  Emissions to water   
2588                                    γ-butyrolactone    Emissions to air   
2589                                    γ-butyrolactone  Emissions to water   

                                      subcompartment unitName  index  \
0     Emissions to non-urban air or from high stacks       kg      0   
1                     Emissions to agricultural soil       kg      1   
2                     Emissions to agricultural soil       kg      2   
3                      Emissions to air, unspecified       kg      3   
4                     Emissions to agricultural soil       kg      4   
...                                              ...      ...    ...   
2585                  Emissions to agricultural soil       kg   2585   
2586          Emissions to urban air close to ground       kg   2586   
2587                        Emissions to fresh water       kg   2587   
2588                   Emissions to air, unspecified       kg   2588   
2589                 Emissions to water, unspecified       kg   2589   

      water in wet mass  water region  
0                   0.0           NaN  
1                   0.0           NaN  
2                   0.0           NaN  
3                   0.0           NaN  
4                   0.0           NaN  
...                 ...           ...  
2585                0.0           NaN  
2586                0.0           NaN  
2587                0.0           NaN  
2588                0.0           NaN  
2589                0.0           NaN  

[2590 rows x 7 columns]

In [80]:
type(pickled_data)

matrix_builder.Matrix_Index

In [66]:
pickled_data.dfs['LCIA']

method category                                        indicator  \
0   EF2.0    total                                 EF-Acidification   
1   EF2.0    total                                EF-Climate change   
2   EF2.0    total                       EF-Climate change-Biogenic   
3   EF2.0    total                         EF-Climate change-Fossil   
4   EF2.0    total   EF-Climate change-Land use and land use change   
5   EF2.0    total                       EF-Ecotoxicity, freshwater   
6   EF2.0    total                         EF-Eutrophication marine   
7   EF2.0    total                    EF-Eutrophication, freshwater   
8   EF2.0    total                   EF-Eutrophication, terrestrial   
9   EF2.0    total                        EF-Human toxicity, cancer   
10  EF2.0    total                    EF-Human toxicity, non-cancer   
11  EF2.0    total              EF-Ionising radiation, human health   
12  EF2.0    total                                      EF-Land use   
13  EF2.0    total                               EF-Ozone depletion   
14  EF2.0    total                            EF-particulate Matter   
15  EF2.0    total  EF-Photochemical ozone formation - human health   
16  EF2.0    total                         EF-Resource use, fossils   
17  EF2.0    total             EF-Resource use, minerals and metals   
18  EF2.0    total                                     EF-Water use   

      indicator unitName  index  
0     mol H+ equivalents      0  
1     kg CO2 Equivalents      1  
2     kg CO2 Equivalents      2  
3     kg CO2 Equivalents      3  
4     kg CO2 Equivalents      4  
5                   CTUe      5  
6       kg N equivalents      6  
7       kg P equivalents      7  
8      mol N equivalents      8  
9                   CTUh      9  
10                  CTUh     10  
11  kBq U235 equivalents     11  
12    dimensionless (pt)     12  
13  kg CFC11 equivalents     13  
14     disease incidence     14  
15  kg NMVOC equivalents     15  
16                    MJ     16  
17     kg Sb equivalents     17  
18  m3-world equivalents     18

In [26]:
mydf = pickled_data.dfs['ie']

In [38]:
mydf.head()

activityName geography index  \
0                 [sulfonyl]urea-compound production       RER     0   
1                [thio]carbamate-compound production       RER     1   
2            1,1-difluoroethane production, HFC-152a        US     2   
3  1,1-dimethylcyclopentane to generic market for...       GLO     3   
4                              1-propanol production       RER     4   

                        product unitName  
0       [sulfonyl]urea-compound       kg  
1      [thio]carbamate-compound       kg  
2  1,1-difluoroethane, HFC-152a       kg  
3              solvent, organic       kg  
4                    1-propanol       kg

In [39]:
len(mydf)

15437

In [37]:
tuple(mydf.loc[mydf0, ['activityName', 'geography', 'product']])

('[sulfonyl]urea-compound production', 'RER', '[sulfonyl]urea-compound')

In [47]:
mydf.loc[0:3, ['activityName', 'geography', 'product']]

activityName geography  \
0                 [sulfonyl]urea-compound production       RER   
1                [thio]carbamate-compound production       RER   
2            1,1-difluoroethane production, HFC-152a        US   
3  1,1-dimethylcyclopentane to generic market for...       GLO   

                        product  
0       [sulfonyl]urea-compound  
1      [thio]carbamate-compound  
2  1,1-difluoroethane, HFC-152a  
3              solvent, organic

In [56]:
len(mydf.loc[0:3])

4

In [62]:
mylist = [tuple(mydf.loc[x, ['activityName', 'geography', 'product']]) for x in range(len(mydf.loc[0:3]))]

In [63]:
mylist

[('[sulfonyl]urea-compound production', 'RER', '[sulfonyl]urea-compound'),
 ('[thio]carbamate-compound production', 'RER', '[thio]carbamate-compound'),
 ('1,1-difluoroethane production, HFC-152a',
  'US',
  '1,1-difluoroethane, HFC-152a'),
 ('1,1-dimethylcyclopentane to generic market for solvent, organic',
  'GLO',
  'solvent, organic')]

In [ ]:
cols = ['activityName', 'geography', 'product', 'unitName']
dt.set_index(cols[:3])

In [ ]:
li = [{'activityName': 'fa', 'geography': 'idri', 'product': 'soh', 'unitName': 'hish', 'index': 'ham'}, {'activityName': 'da', 'geography': 'idrf', 'product': 'sob', 'unitName': 'his', 'index': 'bam'}]

In [ ]:
df = pd.DataFrame(li)
df

In [ ]:
df.transpose()

In [ ]:
type(pickled_data.units)

In [ ]:
set_index = True
columns = ['method', 'category', 'indicator']
pickled_data.dfs["LCIA"].True(columns[:3])

In [13]:
pickled_data.toggle["ie"][0]

('[sulfonyl]urea-compound production', 'RER', '[sulfonyl]urea-compound')

In [15]:
pickled_data.toggle["ie"][('[sulfonyl]urea-compound production', 'RER', '[sulfonyl]urea-compound')]

0

In [10]:
df = pd.DataFrame({'month': [],'year': [],'sale': []})
df
len(df)

0

In [12]:
0 == False

True

In [27]:
df = pd.read_excel(r'D:\ecoinvent_scripts\PEF_Project\ILCD_Reader\Data\input\excel\indexes_PEF-phase 2-start_Allocation, cut-off.xlsx', sheet_name="ie")

In [56]:
result = df.loc[df.index==0, ["activityName","geography","product"]].values

In [57]:
result

array([['[sulfonyl]urea-compound production', 'RER',
        '[sulfonyl]urea-compound']], dtype=object)

In [55]:
tuple(next(iter(result.values)))

('[sulfonyl]urea-compound production', 'RER', '[sulfonyl]urea-compound')

In [2]:
os.getcwd()

'C:\\Users\\Faysal\\AppData\\Local\\Temp\\0f6d978b-a2b4-4981-aa02-44fdd024455c'

In [4]:
os.chdir(r'D:\ecoinvent_scripts')

In [5]:
with open(r"C:\Dropbox (ecoinvent)\ei-int\technical\external\PEF\PEF follow-up\execution\06_matrixFlowChanges\in\pilotPhase_water_correction\B.pkl", 'rb') as file:
    data = pickle.load(file)

In [6]:
type(data)

scipy.sparse.csc.csc_matrix

In [7]:
data

<41510x15437 sparse matrix of type '<class 'numpy.float64'>'
	with 1646196 stored elements in Compressed Sparse Column format>

In [8]:
import numpy as np

In [12]:
mat = np.ones((5,8))
mat

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
vec = np.ones((1,5))
mylist = [2,4]
vec[0,mylist]=1000
vec

array([[   1.,    1., 1000.,    1., 1000.]])

In [27]:
row_list = [0,2,4]
col_list = [1,3,5]
mat[row_list, col_list] = 100
mat

array([[  1., 100.,   1.,   1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1., 100.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1., 100.,   1.,   1.]])

In [ ]:
mat1[row_list,1]

In [15]:
from scipy.sparse import coo_matrix

In [23]:
row  = np.array([0, 2, 0, 4, 1, 0, 0])
col  = np.array([0, 3, 1, 5, 1, 3, 5])
data = np.array([2, 2, 2, 2, 2, 2, 2])
A = coo_matrix((data, (row, col)), shape=(5, 8)).tocsc()

In [24]:
A.toarray()

array([[2, 2, 0, 2, 0, 2, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0]], dtype=int32)

In [25]:
coo = A.multiply(mat)
newcsc = coo.tocsc()
newcsc.toarray()

array([[  2., 200.,   0.,   2.,   0.,   2.,   0.,   0.],
       [  0.,   2.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 200.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 200.,   0.,   0.]])

In [9]:
data.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [10]:
data.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [1]:
data

NameError: name 'data' is not defined

In [19]:
print(data)

(12855, 0)	0.00011145
  (12871, 0)	0.010687
  (15680, 0)	0.085507
  (15889, 0)	0.56976
  (15962, 0)	0.12826
  (16642, 0)	0.91455
  (16668, 0)	0.0010961
  (16741, 0)	0.00027066
  (16745, 0)	0.00042882
  (16895, 0)	9.6489e-05
  (16899, 0)	0.00024062
  (17988, 0)	7.9021e-05
  (19344, 0)	0.00012131
  (19348, 0)	0.00029115
  (20255, 0)	9.9092e-05
  (20376, 0)	0.00048049
  (21641, 0)	4.2695e-05
  (21645, 0)	0.016157
  (22934, 0)	0.0095927
  (23285, 0)	3.2322913372072217
  (23287, 0)	0.11603014252429802
  (23289, 0)	3.9992524402937613
  (23290, 0)	0.30623721280890653
  (23293, 0)	4.077717320163446
  (23298, 0)	1.3783293585035827
  :	:
  (41055, 15435)	0.1534589139757755
  (41079, 15435)	0.14887642499187914
  (12854, 15436)	6.3e-08
  (13741, 15436)	2.29950016958734e-08
  (13877, 15436)	9.44998870548332e-11
  (15624, 15436)	3.15e-11
  (15626, 15436)	9.0556093951385e-10
  (15888, 15436)	0.00978858690785755
  (17101, 15436)	1.575e-10
  (17650, 15436)	0.00555560091577162
  (17780, 15436)	5.3550011

In [16]:
import scipy.sparse

In [20]:
df = pd.read_excel(r"C:\Dropbox (ecoinvent)\ei-int\technical\external\PEF\PEF follow-up\execution\06_matrixFlowChanges\in\water amount and unit correction_20200302.xlsx")

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 7 columns):
type of search       21 non-null object
flow                 21 non-null object
exchange unitName    21 non-null object
compartment          21 non-null object
subcompartment       21 non-null object
amount               15 non-null object
unit                 18 non-null object
dtypes: object(7)
memory usage: 1.3+ KB


In [22]:
sd = df.amount.dropna()

In [23]:
sd

0     /1000
1     /1000
5     /1000
6     /1000
8     /1000
9     /1000
11    /1000
13    /1000
14    /1000
15    /1000
16    /1000
17    /1000
18    /1000
19    /1000
20    /1000
Name: amount, dtype: object

In [29]:
dropped_df = df.dropna(subset=['amount'])

In [27]:
df_index = pd.read_excel(r"C:\Dropbox (ecoinvent)\ei-int\technical\external\PEF\PEF follow-up\execution\06_matrixFlowChanges\in\pilotPhase_water_correction\indexes_PEF-phase 2-start_Allocation, cut-off.xlsx" , sheet_name='ee')

In [28]:
df_index.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41510 entries, 0 to 41509
Data columns (total 5 columns):
name              41510 non-null object
compartment       41510 non-null object
subcompartment    41510 non-null object
unitName          41510 non-null object
index             41510 non-null int64
dtypes: int64(1), object(4)
memory usage: 1.6+ MB


In [30]:
df1 = pd.DataFrame({'City': ['New York', 'Chicago', 'Tokyo', 'Paris','New Delhi'],
                     'Temp': [59, 29, 73, 56,48]})
df2 = pd.DataFrame({'City': ['London', 'New York', 'Tokyo', 'New Delhi','Paris'],
                     'Temp': [55, 55, 73, 85,56]})

In [31]:
df1

City  Temp
0   New York    59
1    Chicago    29
2      Tokyo    73
3      Paris    56
4  New Delhi    48

In [32]:
df2

City  Temp
0     London    55
1   New York    55
2      Tokyo    73
3  New Delhi    85
4      Paris    56

In [34]:
df1.merge(df2, how='left', indicator=False)

City  Temp
0   New York    59
1    Chicago    29
2      Tokyo    73
3      Paris    56
4  New Delhi    48

In [37]:
filter = df_index['name'].str.contains("regionalized", regex=True)

In [88]:
df_index.loc[filter, 'name'] = df_index.loc[filter,'name'].str.split(',').str[0:2].str.join(',')

In [89]:
df_index.shape

(41510, 5)

In [90]:
df_index.to_excel('test.xlsx')

In [44]:
new_df_index['name'].head()

17512    collected rainwater to lake, regionalized, AR
17513    collected rainwater to lake, regionalized, AT
17514    collected rainwater to lake, regionalized, AU
17515    collected rainwater to lake, regionalized, BA
17516    collected rainwater to lake, regionalized, BD
Name: name, dtype: object

In [78]:
new_df_index['name'] = new_df_index['name'].str.split(',').str[0:2].str.join(',')

In [79]:
new_df_index['name'].head()

17512    collected rainwater to lake, regionalized
17513    collected rainwater to lake, regionalized
17514    collected rainwater to lake, regionalized
17515    collected rainwater to lake, regionalized
17516    collected rainwater to lake, regionalized
Name: name, dtype: object

In [80]:
new_df_index.head()

name         compartment  \
17512  collected rainwater to lake, regionalized  Emissions to water   
17513  collected rainwater to lake, regionalized  Emissions to water   
17514  collected rainwater to lake, regionalized  Emissions to water   
17515  collected rainwater to lake, regionalized  Emissions to water   
17516  collected rainwater to lake, regionalized  Emissions to water   

                 subcompartment unitName  index  
17512  Emissions to fresh water       kg  17512  
17513  Emissions to fresh water       kg  17513  
17514  Emissions to fresh water       kg  17514  
17515  Emissions to fresh water       kg  17515  
17516  Emissions to fresh water       kg  17516

In [81]:
dropped_df

type of search                                               flow  \
0     begins with               cooling water to river, regionalized   
1     begins with                          fresh water, regionalized   
5      flow match                              lake water to turbine   
6     begins with                lake water to turbine, regionalized   
8     begins with       processed water to groundwater, regionalized   
9     begins with             processed water to river, regionalized   
11    begins with               river water to turbine, regionalized   
13    begins with              turbined water to river, regionalized   
14     flow match                                              water   
15     flow match                                              water   
16     flow match    Water (river water from technosphere, turbined)   
17     flow match  Water (sea water from technosphere, cooling wa...   
18     flow match   Water (sea water from technosphere, waste water)   
19     flow match         water, cooling, unspecified natural origin   
20     flow match     water, turbine use, unspecified natural origin   

   exchange unitName             compartment  \
0                 kg      Emissions to water   
1                 kg               Resources   
5                 kg               Resources   
6                 kg               Resources   
8                 kg      Emissions to water   
9                 kg      Emissions to water   
11                kg               Resources   
13                kg      Emissions to water   
14                m3      Emissions to water   
15                kg               Resources   
16                kg      Emissions to water   
17                kg  Emissions to sea water   
18                kg  Emissions to sea water   
19                m3               Resources   
20                m3               Resources   

                             subcompartment amount unit  
0                  Emissions to fresh water  /1000   m3  
1   Renewable material resources from water  /1000   m3  
5   Renewable material resources from water  /1000   m3  
6   Renewable material resources from water  /1000   m3  
8                  Emissions to fresh water  /1000   m3  
9                  Emissions to fresh water  /1000   m3  
11  Renewable material resources from water  /1000   m3  
13                 Emissions to fresh water  /1000   m3  
14                 Emissions to fresh water  /1000  NaN  
15  Renewable material resources from water  /1000   m3  
16                 Emissions to fresh water  /1000   m3  
17             Other emissions to sea water  /1000   m3  
18             Other emissions to sea water  /1000   m3  
19  Renewable material resources from water  /1000  NaN  
20  Renewable material resources from water  /1000  NaN

In [91]:
left_cols = ['name', 'compartment', 'subcompartment']
right_cols = ['flow', 'compartment', 'subcompartment']
merged_df = pd.merge(df_index, dropped_df, left_on=left_cols, right_on=right_cols, how="inner")

In [92]:
merged_df.head()

name         compartment  \
0  cooling water to river, regionalized  Emissions to water   
1  cooling water to river, regionalized  Emissions to water   
2  cooling water to river, regionalized  Emissions to water   
3  cooling water to river, regionalized  Emissions to water   
4  cooling water to river, regionalized  Emissions to water   

             subcompartment unitName  index type of search  \
0  Emissions to fresh water       kg  17714    begins with   
1  Emissions to fresh water       kg  17715    begins with   
2  Emissions to fresh water       kg  17716    begins with   
3  Emissions to fresh water       kg  17717    begins with   
4  Emissions to fresh water       kg  17718    begins with   

                                   flow exchange unitName amount unit  
0  cooling water to river, regionalized                kg  /1000   m3  
1  cooling water to river, regionalized                kg  /1000   m3  
2  cooling water to river, regionalized                kg  /1000   m3  
3  cooling water to river, regionalized                kg  /1000   m3  
4  cooling water to river, regionalized                kg  /1000   m3

In [93]:
merged_df.shape

(449, 10)

In [94]:
merged_df.to_excel('sample.xlsx')

In [95]:
data

<41510x15437 sparse matrix of type '<class 'numpy.float64'>'
	with 1646196 stored elements in Compressed Sparse Column format>

In [96]:
print(data)

(12855, 0)	0.00011145
  (12871, 0)	0.010687
  (15680, 0)	0.085507
  (15889, 0)	0.56976
  (15962, 0)	0.12826
  (16642, 0)	0.91455
  (16668, 0)	0.0010961
  (16741, 0)	0.00027066
  (16745, 0)	0.00042882
  (16895, 0)	9.6489e-05
  (16899, 0)	0.00024062
  (17988, 0)	7.9021e-05
  (19344, 0)	0.00012131
  (19348, 0)	0.00029115
  (20255, 0)	9.9092e-05
  (20376, 0)	0.00048049
  (21641, 0)	4.2695e-05
  (21645, 0)	0.016157
  (22934, 0)	0.0095927
  (23285, 0)	3.2322913372072217
  (23287, 0)	0.11603014252429802
  (23289, 0)	3.9992524402937613
  (23290, 0)	0.30623721280890653
  (23293, 0)	4.077717320163446
  (23298, 0)	1.3783293585035827
  :	:
  (41055, 15435)	0.1534589139757755
  (41079, 15435)	0.14887642499187914
  (12854, 15436)	6.3e-08
  (13741, 15436)	2.29950016958734e-08
  (13877, 15436)	9.44998870548332e-11
  (15624, 15436)	3.15e-11
  (15626, 15436)	9.0556093951385e-10
  (15888, 15436)	0.00978858690785755
  (17101, 15436)	1.575e-10
  (17650, 15436)	0.00555560091577162
  (17780, 15436)	5.3550011

In [98]:
merged_df.head()

name         compartment  \
0  cooling water to river, regionalized  Emissions to water   
1  cooling water to river, regionalized  Emissions to water   
2  cooling water to river, regionalized  Emissions to water   
3  cooling water to river, regionalized  Emissions to water   
4  cooling water to river, regionalized  Emissions to water   

             subcompartment unitName  index type of search  \
0  Emissions to fresh water       kg  17714    begins with   
1  Emissions to fresh water       kg  17715    begins with   
2  Emissions to fresh water       kg  17716    begins with   
3  Emissions to fresh water       kg  17717    begins with   
4  Emissions to fresh water       kg  17718    begins with   

                                   flow exchange unitName amount unit  
0  cooling water to river, regionalized                kg  /1000   m3  
1  cooling water to river, regionalized                kg  /1000   m3  
2  cooling water to river, regionalized                kg  /1000   m3  
3  cooling water to river, regionalized                kg  /1000   m3  
4  cooling water to river, regionalized                kg  /1000   m3

In [100]:
merged_df.loc[merged_df['index'] == 17714]

name         compartment  \
0  cooling water to river, regionalized  Emissions to water   

             subcompartment unitName  index type of search  \
0  Emissions to fresh water       kg  17714    begins with   

                                   flow exchange unitName amount unit  
0  cooling water to river, regionalized                kg  /1000   m3

In [101]:
dir(data)

['__abs__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmatmul__',
 '__rmul__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_add_dense',
 '_add_sparse',
 '_arg_min_or_max',
 '_arg_min_or_max_axis',
 '_asindices',
 '_binopt',
 '_cs_matrix__get_has_canonical_format',
 '_cs_matrix__get_sorted',
 '_cs_matrix__set_has_canonical_format',
 '_cs_matrix__set_sorted

In [105]:
data.data

array([1.11450000e-04, 1.06870000e-02, 8.55070000e-02, ...,
       3.17519993e-06, 3.15000000e-09, 2.25490115e-06])

In [104]:
data.shape

(41510, 15437)

In [108]:
data

<41510x15437 sparse matrix of type '<class 'numpy.float64'>'
	with 1646196 stored elements in Compressed Sparse Column format>

In [114]:
data.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [116]:
print(data.getrow(23293))

(0, 0)	4.077717320163446
  (0, 1)	3.124879269501579
  (0, 4)	0.493757639666782
  (0, 6)	0.6285902478253113
  (0, 7)	0.6285902478253113
  (0, 8)	4.9763394619503805
  (0, 10)	1.3813532608564476
  (0, 11)	0.6285902478253113
  (0, 12)	0.6285902478253113
  (0, 13)	1.6603163745892555
  (0, 14)	1.3556072519559357
  (0, 15)	0.6285902478253113
  (0, 16)	5.98
  (0, 17)	0.42953666934729606
  (0, 18)	4.72673675104308
  (0, 19)	0.6285902478253113
  (0, 20)	2.0429183054322615
  (0, 21)	9.756244471455352
  (0, 22)	1.4718964478036185
  (0, 23)	1.4442725255377287
  (0, 24)	2.060573847113685
  (0, 26)	0.6285902478253113
  (0, 27)	0.42953666934729606
  (0, 28)	2.879205247643186
  (0, 29)	0.6285902478253113
  :	:
  (0, 15402)	0.139958042313397
  (0, 15404)	0.043690801217958375
  (0, 15405)	0.5897666353209806
  (0, 15406)	0.5934297821242167
  (0, 15407)	0.10424362560124156
  (0, 15408)	0.14360091281803683
  (0, 15409)	0.139958042313397
  (0, 15410)	0.11278948662539726
  (0, 15411)	0.1359516133431128
  (0, 

In [117]:
data.shape

(41510, 15437)

In [118]:
data.getrow(23293).data

array([4.07771732e+00, 3.12487927e+00, 4.93757640e-01, 6.28590248e-01,
       6.28590248e-01, 4.97633946e+00, 1.38135326e+00, 6.28590248e-01,
       6.28590248e-01, 1.66031637e+00, 1.35560725e+00, 6.28590248e-01,
       5.98000000e+00, 4.29536669e-01, 4.72673675e+00, 6.28590248e-01,
       2.04291831e+00, 9.75624447e+00, 1.47189645e+00, 1.44427253e+00,
       2.06057385e+00, 6.28590248e-01, 4.29536669e-01, 2.87920525e+00,
       6.28590248e-01, 4.29536669e-01, 1.20479797e-05, 4.81919190e-06,
       6.15494618e-06, 3.69103289e+00, 4.29536669e-01, 1.13146245e-02,
       4.29536669e-01, 1.58433553e+00, 6.28590248e-01, 6.28904543e-01,
       1.43696629e-05, 3.87149656e-01, 3.87149656e-01, 3.87149656e-01,
       3.87149656e-01, 6.54781508e-06, 3.66680002e+00, 3.66680002e+00,
       6.28590248e-06, 6.28595408e-01, 2.05280899e-01, 6.28590248e-01,
       2.05280899e-01, 4.29536669e-01, 9.22162847e-02, 2.13165430e+00,
       7.85744096e+00, 2.05280899e-01, 1.50000000e-02, 2.20006587e-02,
      

In [119]:
data.getrow(23293).data / 2

array([2.03885866e+00, 1.56243963e+00, 2.46878820e-01, 3.14295124e-01,
       3.14295124e-01, 2.48816973e+00, 6.90676630e-01, 3.14295124e-01,
       3.14295124e-01, 8.30158187e-01, 6.77803626e-01, 3.14295124e-01,
       2.99000000e+00, 2.14768335e-01, 2.36336838e+00, 3.14295124e-01,
       1.02145915e+00, 4.87812224e+00, 7.35948224e-01, 7.22136263e-01,
       1.03028692e+00, 3.14295124e-01, 2.14768335e-01, 1.43960262e+00,
       3.14295124e-01, 2.14768335e-01, 6.02398987e-06, 2.40959595e-06,
       3.07747309e-06, 1.84551645e+00, 2.14768335e-01, 5.65731223e-03,
       2.14768335e-01, 7.92167764e-01, 3.14295124e-01, 3.14452271e-01,
       7.18483146e-06, 1.93574828e-01, 1.93574828e-01, 1.93574828e-01,
       1.93574828e-01, 3.27390754e-06, 1.83340001e+00, 1.83340001e+00,
       3.14295124e-06, 3.14297704e-01, 1.02640449e-01, 3.14295124e-01,
       1.02640449e-01, 2.14768335e-01, 4.61081423e-02, 1.06582715e+00,
       3.92872048e+00, 1.02640449e-01, 7.50000000e-03, 1.10003293e-02,
      

In [121]:
merged_df['index']

0      17714
1      17715
2      17716
3      17717
4      17718
       ...  
444    41079
445    41082
446    41494
447    41497
448    41498
Name: index, Length: 449, dtype: int64

In [123]:
data.getrow(23293).data

array([4.07771732e+00, 3.12487927e+00, 4.93757640e-01, 6.28590248e-01,
       6.28590248e-01, 4.97633946e+00, 1.38135326e+00, 6.28590248e-01,
       6.28590248e-01, 1.66031637e+00, 1.35560725e+00, 6.28590248e-01,
       5.98000000e+00, 4.29536669e-01, 4.72673675e+00, 6.28590248e-01,
       2.04291831e+00, 9.75624447e+00, 1.47189645e+00, 1.44427253e+00,
       2.06057385e+00, 6.28590248e-01, 4.29536669e-01, 2.87920525e+00,
       6.28590248e-01, 4.29536669e-01, 1.20479797e-05, 4.81919190e-06,
       6.15494618e-06, 3.69103289e+00, 4.29536669e-01, 1.13146245e-02,
       4.29536669e-01, 1.58433553e+00, 6.28590248e-01, 6.28904543e-01,
       1.43696629e-05, 3.87149656e-01, 3.87149656e-01, 3.87149656e-01,
       3.87149656e-01, 6.54781508e-06, 3.66680002e+00, 3.66680002e+00,
       6.28590248e-06, 6.28595408e-01, 2.05280899e-01, 6.28590248e-01,
       2.05280899e-01, 4.29536669e-01, 9.22162847e-02, 2.13165430e+00,
       7.85744096e+00, 2.05280899e-01, 1.50000000e-02, 2.20006587e-02,
      

In [127]:
data.getrow(23293).data = data.getrow(23293).data / 2

In [156]:
data.getrow(23293).data

array([4.07771732e+00, 3.12487927e+00, 4.93757640e-01, 6.28590248e-01,
       6.28590248e-01, 4.97633946e+00, 1.38135326e+00, 6.28590248e-01,
       6.28590248e-01, 1.66031637e+00, 1.35560725e+00, 6.28590248e-01,
       5.98000000e+00, 4.29536669e-01, 4.72673675e+00, 6.28590248e-01,
       2.04291831e+00, 9.75624447e+00, 1.47189645e+00, 1.44427253e+00,
       2.06057385e+00, 6.28590248e-01, 4.29536669e-01, 2.87920525e+00,
       6.28590248e-01, 4.29536669e-01, 1.20479797e-05, 4.81919190e-06,
       6.15494618e-06, 3.69103289e+00, 4.29536669e-01, 1.13146245e-02,
       4.29536669e-01, 1.58433553e+00, 6.28590248e-01, 6.28904543e-01,
       1.43696629e-05, 3.87149656e-01, 3.87149656e-01, 3.87149656e-01,
       3.87149656e-01, 6.54781508e-06, 3.66680002e+00, 3.66680002e+00,
       6.28590248e-06, 6.28595408e-01, 2.05280899e-01, 6.28590248e-01,
       2.05280899e-01, 4.29536669e-01, 9.22162847e-02, 2.13165430e+00,
       7.85744096e+00, 2.05280899e-01, 1.50000000e-02, 2.20006587e-02,
      

In [135]:
print(data[23293,:].shape)

(1, 15437)


In [136]:
new_Data = data[23293,:].data / 2

In [137]:
new_Data

array([2.03885866e+00, 1.56243963e+00, 2.46878820e-01, 3.14295124e-01,
       3.14295124e-01, 2.48816973e+00, 6.90676630e-01, 3.14295124e-01,
       3.14295124e-01, 8.30158187e-01, 6.77803626e-01, 3.14295124e-01,
       2.99000000e+00, 2.14768335e-01, 2.36336838e+00, 3.14295124e-01,
       1.02145915e+00, 4.87812224e+00, 7.35948224e-01, 7.22136263e-01,
       1.03028692e+00, 3.14295124e-01, 2.14768335e-01, 1.43960262e+00,
       3.14295124e-01, 2.14768335e-01, 6.02398987e-06, 2.40959595e-06,
       3.07747309e-06, 1.84551645e+00, 2.14768335e-01, 5.65731223e-03,
       2.14768335e-01, 7.92167764e-01, 3.14295124e-01, 3.14452271e-01,
       7.18483146e-06, 1.93574828e-01, 1.93574828e-01, 1.93574828e-01,
       1.93574828e-01, 3.27390754e-06, 1.83340001e+00, 1.83340001e+00,
       3.14295124e-06, 3.14297704e-01, 1.02640449e-01, 3.14295124e-01,
       1.02640449e-01, 2.14768335e-01, 4.61081423e-02, 1.06582715e+00,
       3.92872048e+00, 1.02640449e-01, 7.50000000e-03, 1.10003293e-02,
      

In [138]:
type(new_Data)

numpy.ndarray

In [139]:
import numpy as np

In [140]:
dd = np.copy(new_Data)

In [141]:
dd

array([2.03885866e+00, 1.56243963e+00, 2.46878820e-01, 3.14295124e-01,
       3.14295124e-01, 2.48816973e+00, 6.90676630e-01, 3.14295124e-01,
       3.14295124e-01, 8.30158187e-01, 6.77803626e-01, 3.14295124e-01,
       2.99000000e+00, 2.14768335e-01, 2.36336838e+00, 3.14295124e-01,
       1.02145915e+00, 4.87812224e+00, 7.35948224e-01, 7.22136263e-01,
       1.03028692e+00, 3.14295124e-01, 2.14768335e-01, 1.43960262e+00,
       3.14295124e-01, 2.14768335e-01, 6.02398987e-06, 2.40959595e-06,
       3.07747309e-06, 1.84551645e+00, 2.14768335e-01, 5.65731223e-03,
       2.14768335e-01, 7.92167764e-01, 3.14295124e-01, 3.14452271e-01,
       7.18483146e-06, 1.93574828e-01, 1.93574828e-01, 1.93574828e-01,
       1.93574828e-01, 3.27390754e-06, 1.83340001e+00, 1.83340001e+00,
       3.14295124e-06, 3.14297704e-01, 1.02640449e-01, 3.14295124e-01,
       1.02640449e-01, 2.14768335e-01, 4.61081423e-02, 1.06582715e+00,
       3.92872048e+00, 1.02640449e-01, 7.50000000e-03, 1.10003293e-02,
      

In [142]:
data[23293,:]

<1x15437 sparse matrix of type '<class 'numpy.float64'>'
	with 968 stored elements in Compressed Sparse Column format>

In [155]:
dsa[23293:] = np.copy(data[23293:].data)

NameError: name 'dsa' is not defined

In [152]:
dda.shape

(1180600,)

In [157]:
type(data.getrow(23293).data)

numpy.ndarray

In [160]:
fet = np.copy(data.getrow(23293).data / 2)

In [161]:
fet

array([2.03885866e+00, 1.56243963e+00, 2.46878820e-01, 3.14295124e-01,
       3.14295124e-01, 2.48816973e+00, 6.90676630e-01, 3.14295124e-01,
       3.14295124e-01, 8.30158187e-01, 6.77803626e-01, 3.14295124e-01,
       2.99000000e+00, 2.14768335e-01, 2.36336838e+00, 3.14295124e-01,
       1.02145915e+00, 4.87812224e+00, 7.35948224e-01, 7.22136263e-01,
       1.03028692e+00, 3.14295124e-01, 2.14768335e-01, 1.43960262e+00,
       3.14295124e-01, 2.14768335e-01, 6.02398987e-06, 2.40959595e-06,
       3.07747309e-06, 1.84551645e+00, 2.14768335e-01, 5.65731223e-03,
       2.14768335e-01, 7.92167764e-01, 3.14295124e-01, 3.14452271e-01,
       7.18483146e-06, 1.93574828e-01, 1.93574828e-01, 1.93574828e-01,
       1.93574828e-01, 3.27390754e-06, 1.83340001e+00, 1.83340001e+00,
       3.14295124e-06, 3.14297704e-01, 1.02640449e-01, 3.14295124e-01,
       1.02640449e-01, 2.14768335e-01, 4.61081423e-02, 1.06582715e+00,
       3.92872048e+00, 1.02640449e-01, 7.50000000e-03, 1.10003293e-02,
      

In [164]:
data.getrow(23293).data = data.getrow(23293).data / 2

In [166]:
type(data.getrow(23293))

scipy.sparse.csr.csr_matrix

In [167]:
type(data.getrow(23293).data)

numpy.ndarray

In [170]:
fed = np.copy(data.getrow(23293).data / 2)
np.copyto(data.getrow(23293).data, data.getrow(23293).data / 2)

In [171]:
data.getrow(23293).data

array([4.07771732e+00, 3.12487927e+00, 4.93757640e-01, 6.28590248e-01,
       6.28590248e-01, 4.97633946e+00, 1.38135326e+00, 6.28590248e-01,
       6.28590248e-01, 1.66031637e+00, 1.35560725e+00, 6.28590248e-01,
       5.98000000e+00, 4.29536669e-01, 4.72673675e+00, 6.28590248e-01,
       2.04291831e+00, 9.75624447e+00, 1.47189645e+00, 1.44427253e+00,
       2.06057385e+00, 6.28590248e-01, 4.29536669e-01, 2.87920525e+00,
       6.28590248e-01, 4.29536669e-01, 1.20479797e-05, 4.81919190e-06,
       6.15494618e-06, 3.69103289e+00, 4.29536669e-01, 1.13146245e-02,
       4.29536669e-01, 1.58433553e+00, 6.28590248e-01, 6.28904543e-01,
       1.43696629e-05, 3.87149656e-01, 3.87149656e-01, 3.87149656e-01,
       3.87149656e-01, 6.54781508e-06, 3.66680002e+00, 3.66680002e+00,
       6.28590248e-06, 6.28595408e-01, 2.05280899e-01, 6.28590248e-01,
       2.05280899e-01, 4.29536669e-01, 9.22162847e-02, 2.13165430e+00,
       7.85744096e+00, 2.05280899e-01, 1.50000000e-02, 2.20006587e-02,
      

In [173]:
data[23293,0] = 22

In [175]:
data[23293,:].data

array([2.20000000e+01, 3.12487927e+00, 4.93757640e-01, 6.28590248e-01,
       6.28590248e-01, 4.97633946e+00, 1.38135326e+00, 6.28590248e-01,
       6.28590248e-01, 1.66031637e+00, 1.35560725e+00, 6.28590248e-01,
       5.98000000e+00, 4.29536669e-01, 4.72673675e+00, 6.28590248e-01,
       2.04291831e+00, 9.75624447e+00, 1.47189645e+00, 1.44427253e+00,
       2.06057385e+00, 6.28590248e-01, 4.29536669e-01, 2.87920525e+00,
       6.28590248e-01, 4.29536669e-01, 1.20479797e-05, 4.81919190e-06,
       6.15494618e-06, 3.69103289e+00, 4.29536669e-01, 1.13146245e-02,
       4.29536669e-01, 1.58433553e+00, 6.28590248e-01, 6.28904543e-01,
       1.43696629e-05, 3.87149656e-01, 3.87149656e-01, 3.87149656e-01,
       3.87149656e-01, 6.54781508e-06, 3.66680002e+00, 3.66680002e+00,
       6.28590248e-06, 6.28595408e-01, 2.05280899e-01, 6.28590248e-01,
       2.05280899e-01, 4.29536669e-01, 9.22162847e-02, 2.13165430e+00,
       7.85744096e+00, 2.05280899e-01, 1.50000000e-02, 2.20006587e-02,
      

In [177]:
data

<41510x15437 sparse matrix of type '<class 'numpy.float64'>'
	with 1646196 stored elements in Compressed Sparse Column format>

In [178]:
type(data[23293,:].data)

numpy.ndarray

In [179]:
np.divide(data[23293,:].data, 2)

array([1.10000000e+01, 1.56243963e+00, 2.46878820e-01, 3.14295124e-01,
       3.14295124e-01, 2.48816973e+00, 6.90676630e-01, 3.14295124e-01,
       3.14295124e-01, 8.30158187e-01, 6.77803626e-01, 3.14295124e-01,
       2.99000000e+00, 2.14768335e-01, 2.36336838e+00, 3.14295124e-01,
       1.02145915e+00, 4.87812224e+00, 7.35948224e-01, 7.22136263e-01,
       1.03028692e+00, 3.14295124e-01, 2.14768335e-01, 1.43960262e+00,
       3.14295124e-01, 2.14768335e-01, 6.02398987e-06, 2.40959595e-06,
       3.07747309e-06, 1.84551645e+00, 2.14768335e-01, 5.65731223e-03,
       2.14768335e-01, 7.92167764e-01, 3.14295124e-01, 3.14452271e-01,
       7.18483146e-06, 1.93574828e-01, 1.93574828e-01, 1.93574828e-01,
       1.93574828e-01, 3.27390754e-06, 1.83340001e+00, 1.83340001e+00,
       3.14295124e-06, 3.14297704e-01, 1.02640449e-01, 3.14295124e-01,
       1.02640449e-01, 2.14768335e-01, 4.61081423e-02, 1.06582715e+00,
       3.92872048e+00, 1.02640449e-01, 7.50000000e-03, 1.10003293e-02,
      

In [180]:
data[23293,:].data

array([2.20000000e+01, 3.12487927e+00, 4.93757640e-01, 6.28590248e-01,
       6.28590248e-01, 4.97633946e+00, 1.38135326e+00, 6.28590248e-01,
       6.28590248e-01, 1.66031637e+00, 1.35560725e+00, 6.28590248e-01,
       5.98000000e+00, 4.29536669e-01, 4.72673675e+00, 6.28590248e-01,
       2.04291831e+00, 9.75624447e+00, 1.47189645e+00, 1.44427253e+00,
       2.06057385e+00, 6.28590248e-01, 4.29536669e-01, 2.87920525e+00,
       6.28590248e-01, 4.29536669e-01, 1.20479797e-05, 4.81919190e-06,
       6.15494618e-06, 3.69103289e+00, 4.29536669e-01, 1.13146245e-02,
       4.29536669e-01, 1.58433553e+00, 6.28590248e-01, 6.28904543e-01,
       1.43696629e-05, 3.87149656e-01, 3.87149656e-01, 3.87149656e-01,
       3.87149656e-01, 6.54781508e-06, 3.66680002e+00, 3.66680002e+00,
       6.28590248e-06, 6.28595408e-01, 2.05280899e-01, 6.28590248e-01,
       2.05280899e-01, 4.29536669e-01, 9.22162847e-02, 2.13165430e+00,
       7.85744096e+00, 2.05280899e-01, 1.50000000e-02, 2.20006587e-02,
      

In [181]:
data[23293,:].data = np.divide(data[23293,:].data, 2)

In [182]:
data[23293,:].data

array([2.20000000e+01, 3.12487927e+00, 4.93757640e-01, 6.28590248e-01,
       6.28590248e-01, 4.97633946e+00, 1.38135326e+00, 6.28590248e-01,
       6.28590248e-01, 1.66031637e+00, 1.35560725e+00, 6.28590248e-01,
       5.98000000e+00, 4.29536669e-01, 4.72673675e+00, 6.28590248e-01,
       2.04291831e+00, 9.75624447e+00, 1.47189645e+00, 1.44427253e+00,
       2.06057385e+00, 6.28590248e-01, 4.29536669e-01, 2.87920525e+00,
       6.28590248e-01, 4.29536669e-01, 1.20479797e-05, 4.81919190e-06,
       6.15494618e-06, 3.69103289e+00, 4.29536669e-01, 1.13146245e-02,
       4.29536669e-01, 1.58433553e+00, 6.28590248e-01, 6.28904543e-01,
       1.43696629e-05, 3.87149656e-01, 3.87149656e-01, 3.87149656e-01,
       3.87149656e-01, 6.54781508e-06, 3.66680002e+00, 3.66680002e+00,
       6.28590248e-06, 6.28595408e-01, 2.05280899e-01, 6.28590248e-01,
       2.05280899e-01, 4.29536669e-01, 9.22162847e-02, 2.13165430e+00,
       7.85744096e+00, 2.05280899e-01, 1.50000000e-02, 2.20006587e-02,
      

In [184]:
data[23293,:].shape[1]

15437

In [186]:
for i in range(15437):
    data[23293,i] = np.divide(data[23293,i].data, 2)

KeyboardInterrupt: 

In [191]:
data[23293,3]

0.0

In [197]:
data[23293,:].data

array([4.07771732e+00, 3.12487927e+00, 4.93757640e-01, 6.28590248e-01,
       6.28590248e-01, 4.97633946e+00, 1.38135326e+00, 6.28590248e-01,
       6.28590248e-01, 1.66031637e+00, 1.35560725e+00, 6.28590248e-01,
       5.98000000e+00, 4.29536669e-01, 4.72673675e+00, 6.28590248e-01,
       2.04291831e+00, 9.75624447e+00, 1.47189645e+00, 1.44427253e+00,
       2.06057385e+00, 6.28590248e-01, 4.29536669e-01, 2.87920525e+00,
       6.28590248e-01, 4.29536669e-01, 1.20479797e-05, 4.81919190e-06,
       6.15494618e-06, 3.69103289e+00, 4.29536669e-01, 1.13146245e-02,
       4.29536669e-01, 1.58433553e+00, 6.28590248e-01, 6.28904543e-01,
       1.43696629e-05, 3.87149656e-01, 3.87149656e-01, 3.87149656e-01,
       3.87149656e-01, 6.54781508e-06, 3.66680002e+00, 3.66680002e+00,
       6.28590248e-06, 6.28595408e-01, 2.05280899e-01, 6.28590248e-01,
       2.05280899e-01, 4.29536669e-01, 9.22162847e-02, 2.13165430e+00,
       7.85744096e+00, 2.05280899e-01, 1.50000000e-02, 2.20006587e-02,
      

In [198]:
print(data)

(12855, 0)	0.00011145
  (12871, 0)	0.010687
  (15680, 0)	0.085507
  (15889, 0)	0.56976
  (15962, 0)	0.12826
  (16642, 0)	0.91455
  (16668, 0)	0.0010961
  (16741, 0)	0.00027066
  (16745, 0)	0.00042882
  (16895, 0)	9.6489e-05
  (16899, 0)	0.00024062
  (17988, 0)	7.9021e-05
  (19344, 0)	0.00012131
  (19348, 0)	0.00029115
  (20255, 0)	9.9092e-05
  (20376, 0)	0.00048049
  (21641, 0)	4.2695e-05
  (21645, 0)	0.016157
  (22934, 0)	0.0095927
  (23285, 0)	3.2322913372072217
  (23287, 0)	0.11603014252429802
  (23289, 0)	3.9992524402937613
  (23290, 0)	0.30623721280890653
  (23293, 0)	4.077717320163446
  (23298, 0)	1.3783293585035827
  :	:
  (41055, 15435)	0.1534589139757755
  (41079, 15435)	0.14887642499187914
  (12854, 15436)	6.3e-08
  (13741, 15436)	2.29950016958734e-08
  (13877, 15436)	9.44998870548332e-11
  (15624, 15436)	3.15e-11
  (15626, 15436)	9.0556093951385e-10
  (15888, 15436)	0.00978858690785755
  (17101, 15436)	1.575e-10
  (17650, 15436)	0.00555560091577162
  (17780, 15436)	5.3550011

In [199]:
data.indices

array([12855, 12871, 15680, ..., 37401, 41222, 41224])

In [200]:
data.indptr

array([      0,     110,     220, ..., 1645916, 1646173, 1646196])

In [201]:
data.shape

(41510, 15437)

In [202]:
data.getrow(23293)

<1x15437 sparse matrix of type '<class 'numpy.float64'>'
	with 968 stored elements in Compressed Sparse Row format>

In [203]:
data.getrow(23293).data

array([4.07771732e+00, 3.12487927e+00, 4.93757640e-01, 6.28590248e-01,
       6.28590248e-01, 4.97633946e+00, 1.38135326e+00, 6.28590248e-01,
       6.28590248e-01, 1.66031637e+00, 1.35560725e+00, 6.28590248e-01,
       5.98000000e+00, 4.29536669e-01, 4.72673675e+00, 6.28590248e-01,
       2.04291831e+00, 9.75624447e+00, 1.47189645e+00, 1.44427253e+00,
       2.06057385e+00, 6.28590248e-01, 4.29536669e-01, 2.87920525e+00,
       6.28590248e-01, 4.29536669e-01, 1.20479797e-05, 4.81919190e-06,
       6.15494618e-06, 3.69103289e+00, 4.29536669e-01, 1.13146245e-02,
       4.29536669e-01, 1.58433553e+00, 6.28590248e-01, 6.28904543e-01,
       1.43696629e-05, 3.87149656e-01, 3.87149656e-01, 3.87149656e-01,
       3.87149656e-01, 6.54781508e-06, 3.66680002e+00, 3.66680002e+00,
       6.28590248e-06, 6.28595408e-01, 2.05280899e-01, 6.28590248e-01,
       2.05280899e-01, 4.29536669e-01, 9.22162847e-02, 2.13165430e+00,
       7.85744096e+00, 2.05280899e-01, 1.50000000e-02, 2.20006587e-02,
      

In [204]:
data.getrow(23293) / 2

<1x15437 sparse matrix of type '<class 'numpy.float64'>'
	with 968 stored elements in Compressed Sparse Row format>

In [205]:
data.getrow(23293).data

array([4.07771732e+00, 3.12487927e+00, 4.93757640e-01, 6.28590248e-01,
       6.28590248e-01, 4.97633946e+00, 1.38135326e+00, 6.28590248e-01,
       6.28590248e-01, 1.66031637e+00, 1.35560725e+00, 6.28590248e-01,
       5.98000000e+00, 4.29536669e-01, 4.72673675e+00, 6.28590248e-01,
       2.04291831e+00, 9.75624447e+00, 1.47189645e+00, 1.44427253e+00,
       2.06057385e+00, 6.28590248e-01, 4.29536669e-01, 2.87920525e+00,
       6.28590248e-01, 4.29536669e-01, 1.20479797e-05, 4.81919190e-06,
       6.15494618e-06, 3.69103289e+00, 4.29536669e-01, 1.13146245e-02,
       4.29536669e-01, 1.58433553e+00, 6.28590248e-01, 6.28904543e-01,
       1.43696629e-05, 3.87149656e-01, 3.87149656e-01, 3.87149656e-01,
       3.87149656e-01, 6.54781508e-06, 3.66680002e+00, 3.66680002e+00,
       6.28590248e-06, 6.28595408e-01, 2.05280899e-01, 6.28590248e-01,
       2.05280899e-01, 4.29536669e-01, 9.22162847e-02, 2.13165430e+00,
       7.85744096e+00, 2.05280899e-01, 1.50000000e-02, 2.20006587e-02,
      

In [207]:
data[23293:].data

array([4.07771732e+00, 1.37832936e+00, 2.93174391e+01, ...,
       3.17519993e-06, 3.15000000e-09, 2.25490115e-06])

In [208]:
data[23293:].data = data[23293:].data / 2

In [209]:
data[23293:].data

array([4.07771732e+00, 1.37832936e+00, 2.93174391e+01, ...,
       3.17519993e-06, 3.15000000e-09, 2.25490115e-06])

In [210]:
A = data.tolil()

In [211]:
A

<41510x15437 sparse matrix of type '<class 'numpy.float64'>'
	with 1646196 stored elements in LInked List format>

In [212]:
print(A)

KeyboardInterrupt: 

In [213]:
A[23293:] = data[23293:].data / 2

ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [214]:
data.shape

(41510, 15437)

In [215]:
print(data)

(12855, 0)	0.00011145
  (12871, 0)	0.010687
  (15680, 0)	0.085507
  (15889, 0)	0.56976
  (15962, 0)	0.12826
  (16642, 0)	0.91455
  (16668, 0)	0.0010961
  (16741, 0)	0.00027066
  (16745, 0)	0.00042882
  (16895, 0)	9.6489e-05
  (16899, 0)	0.00024062
  (17988, 0)	7.9021e-05
  (19344, 0)	0.00012131
  (19348, 0)	0.00029115
  (20255, 0)	9.9092e-05
  (20376, 0)	0.00048049
  (21641, 0)	4.2695e-05
  (21645, 0)	0.016157
  (22934, 0)	0.0095927
  (23285, 0)	3.2322913372072217
  (23287, 0)	0.11603014252429802
  (23289, 0)	3.9992524402937613
  (23290, 0)	0.30623721280890653
  (23293, 0)	4.077717320163446
  (23298, 0)	1.3783293585035827
  :	:
  (41055, 15435)	0.1534589139757755
  (41079, 15435)	0.14887642499187914
  (12854, 15436)	6.3e-08
  (13741, 15436)	2.29950016958734e-08
  (13877, 15436)	9.44998870548332e-11
  (15624, 15436)	3.15e-11
  (15626, 15436)	9.0556093951385e-10
  (15888, 15436)	0.00978858690785755
  (17101, 15436)	1.575e-10
  (17650, 15436)	0.00555560091577162
  (17780, 15436)	5.3550011

In [217]:
b = data.toarray()

MemoryError: Unable to allocate array with shape (41510, 15437) and data type float64

In [218]:
data.shape

(41510, 15437)

In [219]:
np.shape(data)

(41510, 15437)

In [220]:
data[23293:].data

array([4.07771732e+00, 1.37832936e+00, 2.93174391e+01, ...,
       3.17519993e-06, 3.15000000e-09, 2.25490115e-06])

In [221]:
data[23293,0]

4.077717320163446

In [222]:
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        if i == 23293:
            data[i,j] = data[i,j] / 2

In [223]:
data[23293:].data

array([2.03885866e+00, 1.37832936e+00, 2.93174391e+01, ...,
       3.17519993e-06, 3.15000000e-09, 2.25490115e-06])

In [225]:
for j in range(data.shape[1]):
     data[23293,j] = data[23293,j] / 2

In [228]:
 data[23293,:].data

array([1.01942933, 0.78121982, 0.        , ..., 0.        , 0.00602822,
       0.        ])

In [231]:
data.getrow(23293).shape

(1, 15437)

In [2]:
from scipy.sparse import csc_matrix
import numpy as np
row = np.array([0, 2, 2, 0, 1, 2])
col = np.array([0, 0, 1, 2, 2, 2])
data = np.array([1, 2, 3, 4, 5, 6])
d = csc_matrix((data, (row, col)), shape=(3, 3))

In [23]:
d.todense()

matrix([[1, 0, 4],
        [0, 0, 5],
        [2, 3, 6]], dtype=int32)

In [65]:
v = np.array([[2,0,2]])
v

array([[2, 0, 2]])

In [67]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [98]:
a = np.ones((3,1))
a[2,] = 5
a

array([[1.],
       [1.],
       [5.]])

In [127]:
d.getrow(2).data

array([60., 30., 20.])

In [124]:
a.getrow(2)

AttributeError: 'numpy.ndarray' object has no attribute 'getrow'

In [99]:
d.toarray()

array([[ 2,  0,  8],
       [ 0,  0,  0],
       [ 4,  6, 12]])

In [117]:
d.getrow(2).data

array([12,  6,  4], dtype=int32)

In [118]:
d.getrow(2).data

array([12,  6,  4], dtype=int32)

In [122]:
d = d.multiply(a)

In [145]:
d.tocsc()

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Column format>

In [146]:
d.toarray()

array([[ 2.,  0.,  8.],
       [ 0.,  0.,  0.],
       [20., 30., 60.]])

In [123]:
d.toarray()

array([[ 2.,  0.,  8.],
       [ 0.,  0.,  0.],
       [20., 30., 60.]])

In [119]:
s.getrow(2).data

array([60., 30., 20.])

In [101]:
s.toarray()

array([[ 2.,  0.,  8.],
       [ 0.,  0.,  0.],
       [20., 30., 60.]])

In [80]:
d.toarray()

array([[ 2,  0,  8],
       [ 0,  0,  0],
       [ 4,  6, 12]])

In [78]:
b = a.T
b.shape

(2, 5)

In [57]:
v.shape

(1, 3)

In [59]:
e = v.transpose()

In [60]:
d = d.multiply(e)

In [62]:
d.todense()

matrix([[ 2,  0,  8],
        [ 0,  0,  0],
        [ 4,  6, 12]])

In [47]:
d.getrow(0).shape

(1, 3)

In [43]:
e = d.getrow(0).transpose()

In [46]:
e.shape

(3, 1)

In [35]:
c = d.getrow(0).data.transpose()

In [37]:
c.shape

(2,)

In [7]:
print(d[2:].data)

[2 3 6]


In [8]:
print(d[2,0])

2


In [3]:
print(d)

(0, 0)	1
  (2, 0)	2
  (2, 1)	3
  (0, 2)	4
  (1, 2)	5
  (2, 2)	6


In [238]:
d.toarray()

array([[1, 0, 4],
       [0, 0, 5],
       [2, 3, 6]], dtype=int32)

In [18]:
print(d[1:2].data)

[5]


In [19]:
d.getrow(1).data

array([5], dtype=int32)

In [253]:
for i in range(d.shape[1]):
    print(i)
    d[2,i] = d[2,i] * 2

0
1
2


In [247]:
d.getrow(2).data

array([2, 3, 6], dtype=int32)

In [249]:
d.shape[1]

3

In [252]:
d.getrow(2).data

array([ 4,  6, 12], dtype=int32)

In [20]:
d.toarray()

array([[1, 0, 4],
       [0, 0, 5],
       [2, 3, 6]], dtype=int32)

In [21]:
mylist = [0,1]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        if i in mylist:
            # d[i,j] = d[i,j] * 2
            d.getrow(i).data = d.getrow(i).data * 2

In [22]:
d.toarray()

array([[1, 0, 4],
       [0, 0, 5],
       [2, 3, 6]], dtype=int32)

In [261]:
with open(r"C:\Dropbox (ecoinvent)\ei-int\technical\external\PEF\PEF follow-up\execution\06_matrixFlowChanges\in\pilotPhase_water_correction\indexes.pkl", 'rb') as file:
    index_file = pickle.load(file)

In [262]:
dir(index_file)

['LCIA',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'add_index',
 'df_columns',
 'dfs',
 'ee',
 'ie',
 'index_types',
 'to_dfs',
 'to_excel',
 'toggle',
 'units']

In [273]:
df_index = pd.read_excel(r"C:\Dropbox (ecoinvent)\ei-int\technical\external\PEF\PEF follow-up\execution\06_matrixFlowChanges\in\pilotPhase_water_correction\indexes_PEF-phase 2-start_Allocation, cut-off.xlsx" , sheet_name='ee')

In [274]:
df_index

name        compartment  \
0                                       (+)-bornan-2-one   Emissions to air   
1                                       (+)-bornan-2-one   Emissions to air   
2                                       (+)-bornan-2-one   Emissions to air   
3                                       (+)-bornan-2-one   Emissions to air   
4                                       (+)-bornan-2-one  Emissions to soil   
...                                                  ...                ...   
41505  volume occupied, final repository for low-acti...          Resources   
41506  volume occupied, final repository for radioact...          Resources   
41507               volume occupied, underground deposit          Resources   
41508                                             arable          Resources   
41509                                        from arable          Resources   

                                       subcompartment unitName  index  
0                       Emissions to air, unspecified       kg      0  
1           Emissions to air, unspecified (long-term)       kg      1  
2      Emissions to non-urban air or from high stacks       kg      2  
3              Emissions to urban air close to ground       kg      3  
4                      Emissions to agricultural soil       kg      4  
...                                               ...      ...    ...  
41505                                        Land use       m3  41505  
41506                                        Land use       m3  41506  
41507                                        Land use       m3  41507  
41508                                        Land use      m2a  41508  
41509                                        Land use       m2  41509  

[41510 rows x 5 columns]

In [268]:
m3_df = df.dropna(subset=['unit'])

In [269]:
m3_df

type of search                                               flow  \
0     begins with               cooling water to river, regionalized   
1     begins with                          fresh water, regionalized   
2      flow match                                       ground water   
3     begins with                         ground water, regionalized   
4      flow match                                         lake water   
5      flow match                              lake water to turbine   
6     begins with                lake water to turbine, regionalized   
7     begins with                           lake water, regionalized   
8     begins with       processed water to groundwater, regionalized   
9     begins with             processed water to river, regionalized   
10     flow match                                        river water   
11    begins with               river water to turbine, regionalized   
12    begins with                          river water, regionalized   
13    begins with              turbined water to river, regionalized   
15     flow match                                              water   
16     flow match    Water (river water from technosphere, turbined)   
17     flow match  Water (sea water from technosphere, cooling wa...   
18     flow match   Water (sea water from technosphere, waste water)   

   exchange unitName             compartment  \
0                 kg      Emissions to water   
1                 kg               Resources   
2                 kg               Resources   
3                 kg               Resources   
4                 kg               Resources   
5                 kg               Resources   
6                 kg               Resources   
7                 kg               Resources   
8                 kg      Emissions to water   
9                 kg      Emissions to water   
10                kg               Resources   
11                kg               Resources   
12                kg               Resources   
13                kg      Emissions to water   
15                kg               Resources   
16                kg      Emissions to water   
17                kg  Emissions to sea water   
18                kg  Emissions to sea water   

                             subcompartment amount unit  
0                  Emissions to fresh water  /1000   m3  
1   Renewable material resources from water  /1000   m3  
2   Renewable material resources from water    NaN   m3  
3   Renewable material resources from water    NaN   m3  
4   Renewable material resources from water    NaN   m3  
5   Renewable material resources from water  /1000   m3  
6   Renewable material resources from water  /1000   m3  
7   Renewable material resources from water    NaN   m3  
8                  Emissions to fresh water  /1000   m3  
9                  Emissions to fresh water  /1000   m3  
10  Renewable material resources from water    NaN   m3  
11  Renewable material resources from water  /1000   m3  
12  Renewable material resources from water    NaN   m3  
13                 Emissions to fresh water  /1000   m3  
15  Renewable material resources from water  /1000   m3  
16                 Emissions to fresh water  /1000   m3  
17             Other emissions to sea water  /1000   m3  
18             Other emissions to sea water  /1000   m3

In [277]:
df_index['newname'] = df_index['name']
df_index.loc[filter, 'newname'] = df_index.loc[filter,'newname'].str.split(',').str[0:2].str.join(',')

In [278]:
df_index.head()

name        compartment  \
0  (+)-bornan-2-one   Emissions to air   
1  (+)-bornan-2-one   Emissions to air   
2  (+)-bornan-2-one   Emissions to air   
3  (+)-bornan-2-one   Emissions to air   
4  (+)-bornan-2-one  Emissions to soil   

                                   subcompartment unitName  index  \
0                   Emissions to air, unspecified       kg      0   
1       Emissions to air, unspecified (long-term)       kg      1   
2  Emissions to non-urban air or from high stacks       kg      2   
3          Emissions to urban air close to ground       kg      3   
4                  Emissions to agricultural soil       kg      4   

            newname  
0  (+)-bornan-2-one  
1  (+)-bornan-2-one  
2  (+)-bornan-2-one  
3  (+)-bornan-2-one  
4  (+)-bornan-2-one

In [280]:
left_cols = ['newname', 'compartment', 'subcompartment']
right_cols = ['flow', 'compartment', 'subcompartment']
merged_index_m3_df = pd.merge(df_index, m3_df, left_on=left_cols, right_on=right_cols, how="left")

In [282]:
merged_index_m3_df.to_excel('m3_index.xlsx')

In [281]:
merged_index_m3_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41510 entries, 0 to 41509
Data columns (total 11 columns):
name                 41510 non-null object
compartment          41510 non-null object
subcompartment       41510 non-null object
unitName             41510 non-null object
index                41510 non-null int64
newname              41510 non-null object
type of search       638 non-null object
flow                 638 non-null object
exchange unitName    638 non-null object
amount               446 non-null object
unit                 638 non-null object
dtypes: int64(1), object(10)
memory usage: 5.1+ MB


In [283]:
merged_index_m3_df.head()

name        compartment  \
0  (+)-bornan-2-one   Emissions to air   
1  (+)-bornan-2-one   Emissions to air   
2  (+)-bornan-2-one   Emissions to air   
3  (+)-bornan-2-one   Emissions to air   
4  (+)-bornan-2-one  Emissions to soil   

                                   subcompartment unitName  index  \
0                   Emissions to air, unspecified       kg      0   
1       Emissions to air, unspecified (long-term)       kg      1   
2  Emissions to non-urban air or from high stacks       kg      2   
3          Emissions to urban air close to ground       kg      3   
4                  Emissions to agricultural soil       kg      4   

            newname type of search flow exchange unitName amount unit  
0  (+)-bornan-2-one            NaN  NaN               NaN    NaN  NaN  
1  (+)-bornan-2-one            NaN  NaN               NaN    NaN  NaN  
2  (+)-bornan-2-one            NaN  NaN               NaN    NaN  NaN  
3  (+)-bornan-2-one            NaN  NaN               NaN    NaN  NaN  
4  (+)-bornan-2-one            NaN  NaN               NaN    NaN  NaN

In [287]:
import os
os.chdir(r'D:\ecoinvent_scripts')

In [285]:
filter = merged_index_m3_df['unit'].str.contains('m3', regex=True, na=False)
merged_index_m3_df.loc[filter, 'unitName'] = merged_index_m3_df.loc[filter, 'unitName'].str.replace('kg', 'm3')

In [288]:
merged_index_m3_df.drop(['newname', 'type of search', 'flow', 'exchange unitName', 'amount', 'unit'], axis=1, inplace=True)

In [289]:
merged_index_m3_df.to_excel('new_index.xlsx')

In [290]:
with open(r"C:\Dropbox (ecoinvent)\ei-int\technical\external\PEF\PEF follow-up\execution\06_matrixFlowChanges\in\pilotPhase_water_correction\indexes.pkl", 'rb') as file:
    index_file = pickle.load(file)

In [293]:
index_file.dfs

{'ie':                                             activityName geography  index  \
 0                     [sulfonyl]urea-compound production       RER      0   
 1                    [thio]carbamate-compound production       RER      1   
 2                1,1-difluoroethane production, HFC-152a        US      2   
 3      1,1-dimethylcyclopentane to generic market for...       GLO      3   
 4                                  1-propanol production       RER      4   
 ...                                                  ...       ...    ...   
 15432                                 viscose production       RER  15432   
 15433                                 viscose production       RER  15433   
 15434                                 viscose production       RER  15434   
 15435                            zinc sulfide production       RoW  15435   
 15436                                         irrigation        ID  15436   
 
                             product unitName  
 0      

In [294]:
merged_index_m3_df.head()

name        compartment  \
0  (+)-bornan-2-one   Emissions to air   
1  (+)-bornan-2-one   Emissions to air   
2  (+)-bornan-2-one   Emissions to air   
3  (+)-bornan-2-one   Emissions to air   
4  (+)-bornan-2-one  Emissions to soil   

                                   subcompartment unitName  index  
0                   Emissions to air, unspecified       kg      0  
1       Emissions to air, unspecified (long-term)       kg      1  
2  Emissions to non-urban air or from high stacks       kg      2  
3          Emissions to urban air close to ground       kg      3  
4                  Emissions to agricultural soil       kg      4

In [300]:
merged_index_m3_df.loc[merged_index_m3_df.unitName == 'm3','unitName'].count()

668

In [303]:
index_file.dfs['ee'].loc[index_file.dfs['ee'].unitName == 'm3', 'unitName'].count()

30

In [304]:
index_file.dfs['ee'] = merged_index_m3_df

In [305]:
index_file.dfs['ee']

name        compartment  \
0                                       (+)-bornan-2-one   Emissions to air   
1                                       (+)-bornan-2-one   Emissions to air   
2                                       (+)-bornan-2-one   Emissions to air   
3                                       (+)-bornan-2-one   Emissions to air   
4                                       (+)-bornan-2-one  Emissions to soil   
...                                                  ...                ...   
41505  volume occupied, final repository for low-acti...          Resources   
41506  volume occupied, final repository for radioact...          Resources   
41507               volume occupied, underground deposit          Resources   
41508                                             arable          Resources   
41509                                        from arable          Resources   

                                       subcompartment unitName  index  
0                       Emissions to air, unspecified       kg      0  
1           Emissions to air, unspecified (long-term)       kg      1  
2      Emissions to non-urban air or from high stacks       kg      2  
3              Emissions to urban air close to ground       kg      3  
4                      Emissions to agricultural soil       kg      4  
...                                               ...      ...    ...  
41505                                        Land use       m3  41505  
41506                                        Land use       m3  41506  
41507                                        Land use       m3  41507  
41508                                        Land use      m2a  41508  
41509                                        Land use       m2  41509  

[41510 rows x 5 columns]

In [306]:
index_file.dfs['ee'].loc[index_file.dfs['ee'].unitName == 'm3', 'unitName'].count()

668

In [307]:
with open('indexx.pkl', 'wb') as file:
    pickle.dump(index_file, file, protocol=pickle.HIGHEST_PROTOCOL)

In [308]:
other_df_index = pd.read_excel(r"C:\Dropbox (ecoinvent)\ei-int\technical\external\PEF\PEF follow-up\execution\06_matrixFlowChanges\in\pilotPhase_water_correction\indexes_PEF-phase 2-start_Allocation, cut-off.xlsx" , sheet_name=None)

In [312]:
other_df_index['ee'] = merged_index_m3_df

In [313]:
other_df_index['ee']

name        compartment  \
0                                       (+)-bornan-2-one   Emissions to air   
1                                       (+)-bornan-2-one   Emissions to air   
2                                       (+)-bornan-2-one   Emissions to air   
3                                       (+)-bornan-2-one   Emissions to air   
4                                       (+)-bornan-2-one  Emissions to soil   
...                                                  ...                ...   
41505  volume occupied, final repository for low-acti...          Resources   
41506  volume occupied, final repository for radioact...          Resources   
41507               volume occupied, underground deposit          Resources   
41508                                             arable          Resources   
41509                                        from arable          Resources   

                                       subcompartment unitName  index  
0                       Emissions to air, unspecified       kg      0  
1           Emissions to air, unspecified (long-term)       kg      1  
2      Emissions to non-urban air or from high stacks       kg      2  
3              Emissions to urban air close to ground       kg      3  
4                      Emissions to agricultural soil       kg      4  
...                                               ...      ...    ...  
41505                                        Land use       m3  41505  
41506                                        Land use       m3  41506  
41507                                        Land use       m3  41507  
41508                                        Land use      m2a  41508  
41509                                        Land use       m2  41509  

[41510 rows x 5 columns]

In [316]:
with pd.ExcelWriter('other_df.xlsx') as writer:
            other_df_index['ie'].to_excel(writer, sheet_name='ie', index=False)
            other_df_index['ee'].to_excel(writer, sheet_name='ee', index=False)
            other_df_index['LCIA'].to_excel(writer, sheet_name='LCIA', index=False)

In [157]:
with open(r"D:\ecoinvent_scripts\B.pkl", 'rb') as file:
    modified_data = pickle.load(file)

In [158]:
data.getrow(17714).data

array([1.00987142e-09, 2.31445394e-07, 2.02698510e-07, ...,
       1.91973163e-07, 2.37185734e-11, 1.30613389e-07])

In [159]:
modified_data.getrow(17714).data

array([1.00987142e-12, 2.31445394e-10, 2.02698510e-10, ...,
       1.91973163e-10, 2.37185734e-14, 1.30613389e-10])

In [142]:
np.array_equal(data.getrow(17714).data, modified_data.getrow(17714).data)

False

In [160]:
data.getrow(12871).data

array([1.0687000e-02, 2.6559000e-03, 3.1121000e-03, ..., 8.4706087e-14,
       1.5200000e-09, 3.4000000e-04])

In [161]:
modified_data.getrow(12871).data

array([1.0687000e-02, 2.6559000e-03, 3.1121000e-03, ..., 8.4706087e-14,
       1.5200000e-09, 3.4000000e-04])

In [143]:
np.array_equal(data.getrow(12871).data, modified_data.getrow(12871).data)

False

In [162]:
data.getrow(17715).data

array([8.34989314e-05, 5.73443489e-02, 5.68728988e-05, ...,
       8.91891299e-05, 1.03271149e-05, 2.33897284e-04])

In [163]:
modified_data.getrow(17715).data

array([8.34989314e-08, 5.73443489e-05, 5.68728988e-08, ...,
       8.91891299e-08, 1.03271149e-08, 2.33897284e-07])